# Generated by Django 4.1.7 on 2023-04-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
